CREATE TABLE usuarios (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome VARCHAR(150) NOT NULL CHECK (btrim(nome) <> ''),
 email VARCHAR(254) NOT NULL UNIQUE CHECK (btrim(email) <> ''),
 senha_hash VARCHAR(255) NOT NULL
);
CREATE TABLE lojas (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome VARCHAR(150) NOT NULL CHECK (btrim(nome) <> '')
);
CREATE TABLE produtos (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 codigo VARCHAR(60) NOT NULL UNIQUE CHECK (codigo = upper(btrim(codigo)) AND codigo <> ''),
 nome VARCHAR(150) NOT NULL CHECK (btrim(nome) <> '')
);
CREATE TABLE estoques (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 loja_id BIGINT NOT NULL REFERENCES lojas(id),
 produto_id BIGINT NOT NULL REFERENCES produtos(id),
 quantidade INTEGER NOT NULL CHECK (quantidade >= 0),
 CONSTRAINT uk_estoque_loja_produto UNIQUE (loja_id, produto_id)
);
CREATE TABLE transferencias (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 produto_id BIGINT NOT NULL REFERENCES produtos(id),
 loja_origem_id BIGINT NOT NULL REFERENCES lojas(id),
 loja_destino_id BIGINT NOT NULL REFERENCES lojas(id),
 quantidade INTEGER NOT NULL CHECK (quantidade > 0),
 data_hora TIMESTAMP WITH TIME ZONE NOT NULL,
 usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
 CHECK (loja_origem_id <> loja_destino_id)
);
CREATE INDEX idx_transferencias_data_hora ON transferencias(data_hora DESC, id DESC);
